org: jovial
service: credit-card-validator

provider:
  name: aws
  runtime: nodejs20.x

functions:
  validate:
    handler: handler.validateCard
    events:
      - httpApi:
          path: /validate
          method: post
plugins:
  - serverless-offline
